### ISSUE TITLE
CKB Indexer references are conflicting

### ISSUE THREAD

**Issue by TravisLeeRichardson** [nervosnetwork/docs.nervos.org#152]
On this page, "https://docs.nervos.org/docs/integrate/introduction," we find the following statements:

_1. "It is not recommended to use the ckb node internal Indexer module to collect live cells, which is very slow and deprecated." 
2. "You may also need an indexer to index live cells and transactions, and then you can try [CKB Indexer](https://github.com/nervosnetwork/ckb-indexer). If you are looking for a one-stop solution that includes both node and indexer, you can try Perkins' Tent."_

However, we also have on the same page:

_"Since v0.105.0, CKB has integrated the functions in previous standalone ckb-indexers. Users of v0.105.0 nodes or above have no need to start ckb-indexer service separately. Ckb-indexer-related RPC is included in the current RPC as a module. Users don't have to configure the indexer port separately."_

So for me, number 1 seems conflicting. Number 2 also seems possibly deprecated with the reference to Perkins' tent. I think we need to be more clear about the preferred method of operation, with the caveat of how to run indexer on its own if so desired.

**Comment by zhangsoledad** [comment]
Associated https://github.com/nervosnetwork/docs-new/issues/160

**Comment by zhangsoledad** [comment]
The outdated inconsistencies have been fixed, if you find there is still something ambiguous and misunderstood, feel free reopen.
