### ISSUE TITLE
Docs: Docker link broken

### ISSUE THREAD

**Issue by roughpandaz** [nervosnetwork/docs.nervos.org#195]
### Issue
Docker link in [guide](https://docs.nervos.org/docs/basics/guides/testnet) goes to 404 error page: 
`Alternatively, you can also use [Docker](https://github.com/nervosnetwork/ckb/blob/develop/docs/run-ckb-with-docker.md) if your operating system`
[Github docs link](https://github.com/nervosnetwork/docs.nervos.org/blob/6d30ec37ab75476a75d8dbb33e9b20ce1bcaaa39/website/docs/basics/guides/testnet.md)

### Solution
Link to docker hub`https://hub.docker.com/r/nervos/ckb`

### Question
CKB Docker says it's running EagleSong algorithm for mining. However, the [docs recommend](https://docs.nervos.org/docs/basics/guides/devchain/#setup-an-eaglesong-worker-blockchain) to run `Dummy-Worker`. Am I missing something?

**Comment by eval-exec** [comment]
[Dummy-Worker](https://docs.nervos.org/docs/basics/guides/devchain/#setup-a-dummy-worker-blockchain) is used for development scenarios. [EagleSong](https://docs.nervos.org/docs/basics/guides/devchain/#setup-an-eaglesong-worker-blockchain) is used in CKB mainnet.
