### ISSUE TITLE
Docs v2: Address and Wallet recommendations.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/docs.nervos.org#266]
- [x] Wallets are not really a concept. I would remove this from this section. We should have a separate section for wallets and/or recommended software.
- [x] Both bech32 and bech32m are mentioned. Which one is more correct? Probably bech32m. Only mention that.
- [x] Nothing is mentioned about ckb vs ckt for testnet.
- [x] It says "The address formats below have been deprecated:" then lists both short and long underneath. It is unclear that long is the proper format to use.
- [x] There are two full address examples in close proximity. We only need one.
- [x] We have been referring to the current address standard as "CKB2021 addresses" in some other places.
- [x] The mention of short addresses and deprecation should be a side note after all information about the full address format. The focus of the page is the current format, with a note about the old format. Most of the ecosystem has successfully transitioned already.
- [x] 61 CKB is the bare minimum. In some other places the recommendation was changed to 62 CKB to allow extra for fees.

**Comment by roughpandaz** [comment]
Thanks man! These are amazing suggestions. We are updating these in the current PR!

**Comment by roughpandaz** [comment]
@linnnsss @yfeng2824  Do we need a section to discuss testnets?
