### ISSUE TITLE
Capacity collection bug in example code.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/docs.nervos.org#301]
In some of the `lib.ts` files there is a bug with capacity collection.

```
if (collectedSum >= neededCapacity) break;
```

These are instances of BI, so it should be `collectedSum.gte(neededCapacity)`.

**Comment by RetricSu** [comment]
I see, we will pull a fix soon

**Comment by RetricSu** [comment]
- https://github.com/nervosnetwork/docs.nervos.org/pull/313
