### ISSUE TITLE
Docs v3: Restructure Sidebar, Main Content, and TOC for Better Visuals

### ISSUE THREAD

**Issue by yfeng2824** [nervosnetwork/docs.nervos.org#375]
**Description**
Consider improving the visual structure of our documentation by resizing the sidebar, main content area, and the table of contents (TOC) on the right side. 

**Tasks**
- Resize the sidebar to a more compact width. Make the texts smaller to display more contents.
- Adjust the main content area for optimal readability.
- Resize the TOC on the right side to ensure it complements the main content without overpowering it.
- Ensure the new layout is responsive and works well on various screen sizes.

**Reference**
- Example layout: [refine.dev documentation](https://refine.dev/docs/getting-started/quickstart/#using-cli)

**Comment by RetricSu** [comment]
- https://github.com/nervosnetwork/docs.nervos.org/pull/380
