### ISSUE TITLE
put deps/tool lock version for every docs

### ISSUE THREAD

**Issue by RetricSu** [nervosnetwork/docs.nervos.org#463]
right now in every doc page we wrote, there is no clearifications about the requirement of lock-version for related deps/library/tools. This causes problems now since a lot of tools/libs are updatding with breaking change for CKB 119 hardforks. 

Two things needed here:
1. refactor Tutorial Overview in tutorial
   - topics feels not very useful and can be removed.
   - refactor Tools You Need: a new better structure with lock-version and maybe we should add platform support information?(like linux, windows, mac)
2. for non-tutorial docs, there often involves a specific version of tools/libs, maybe it needs a overview section too.

**Comment by barCode3** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme

you may need to install the c compiler
